import { Component, OnInit } from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  Validators,
  ReactiveFormsModule,
} from '@angular/forms';
import { CommonModule } from '@angular/common'; // Required for ngIf, ngFor etc.
import { Scholar } from '../../interfaces/scholar';

// Define the Scholar interface based on your provided structure
// We'll exclude pickUpSchedule for now as requested.

@Component({
  selector: 'app-create-scholar',
  standalone: true, // Marking as standalone component for modern Angular
  imports: [
    CommonModule,
    ReactiveFormsModule, // Essential for reactive forms
  ],
  templateUrl: './create-scholar.component.html',
  styleUrls: ['./create-scholar.component.css'], // You can create this file if needed
})
export class CreateScholarComponent implements OnInit {
  // FormGroup to manage the scholar creation form
  scholarForm!: FormGroup;

  // Inject FormBuilder to help create the form group
  constructor(private fb: FormBuilder) {}

  ngOnInit(): void {
    // Initialize the form when the component starts
    this.initForm();
  }

  /**
   * Initializes the reactive form with controls and validators.
   */
  private initForm(): void {
    this.scholarForm = this.fb.group({
      firstName: ['', Validators.required], // First name is required
      lastName: ['', Validators.required], // Last name is required
      schoolId: ['', Validators.required], // School ID is required
      grade: [
        null, // Initial value is null
        [
          Validators.required, // Grade is required
          Validators.min(0), // Minimum grade can be 0 (e.g., kindergarten)
          Validators.max(12), // Maximum grade typically 12
        ],
      ],
      birthDate: [
        '', // Initial value is an empty string
        [
          Validators.required, // Birth date is required
          this.dateValidator, // Custom validator for date format (optional, but good practice)
        ],
      ],
    });
  }

  dateValidator(control: { value: string | number | Date }) {
    if (!control.value) {
      return null;
    }
    const date = new Date(control.value);
    if (isNaN(date.getTime()) || date > new Date()) {
      return { invalidDate: true };
    }
    return null;
  }

  onSubmit(): void {
    if (this.scholarForm.valid) {
      // Create a new scholar object from the form value
      // Note: 'id' will typically be generated by the backend or a service.
      // 'pickUpSchedule' is omitted as per the request.
      const newScholar: Scholar = {
        id: 'temp-id-' + Date.now(), // Placeholder ID
        firstName: this.scholarForm.value.firstName,
        lastName: this.scholarForm.value.lastName,
        pickUpSchedule: null,
        schoolId: this.scholarForm.value.schoolId,
        grade: this.scholarForm.value.grade,
        birthDate: new Date(this.scholarForm.value.birthDate), // Convert string to Date object
      };

      console.log('Form submitted successfully:', newScholar);
      // Here you would typically call a service to save the newScholar data
      // e.g., this.scholarService.createScholar(newScholar).subscribe(...)

      // Optionally reset the form after successful submission
      this.scholarForm.reset();
    } else {
      // If the form is invalid, mark all controls as touched to display validation errors
      this.scholarForm.markAllAsTouched();
      console.log('Form is invalid. Please correct the errors.');
    }
  }
}
