<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <UserSecretsId>d0af71d4-294a-4a18-9be7-d5e426e12e1e</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.Data.SqlClient" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    </ItemGroup>

</Project>
